In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds=pd.read_csv("spam.csv",encoding="latin1")

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [4]:
ds.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [5]:
ds.tail()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [6]:
ds.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [7]:
ds.shape

(5572, 5)

In [8]:
#Problems/Assumptions
# 1.unnamed 2 and unnamed 3,4 have NaN values 50,12,6 resp
#2,rename v1 and v2 with new name
#3.check duplicates, 403 duplicates are there
#4. after deleting reset the index
#5. Do Label encoding with 0 and 1
#6. lower case the message column cause of this all capital letters becomes small
#7. IMP Tokenization process-> breaking a sentence into small piece
#Ex. input:the cat sits after tokenization_-> the,cat,sits
#8. remove punctuations like ., so as ex it appear only cat not cat,
# use this->[^a-zA-Z0-9 ] means keep only letters delete evrything else

In [9]:
ds.isnull().sum() #checking which column have empty or nan values

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [10]:
ds=ds.drop(columns=["Unnamed: 2"])

In [11]:
ds=ds.drop(columns=["Unnamed: 3","Unnamed: 4"])

In [12]:
ds=ds.rename(columns={"v1":"Category","v2":"Message"})

In [13]:
ds.duplicated().sum()

403

In [14]:
ds=ds.drop_duplicates(keep="first")

In [15]:
ds.shape

(5169, 2)

In [16]:
ds.tail()

     Category                                            Message
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

In [17]:
ds=ds.reset_index(drop=True)

In [18]:
mapping={"ham":0,"spam":1}
ds["Category"]=ds["Category"].map(mapping)

In [19]:
ds["Message"]=ds["Message"].str.lower()

In [20]:
ds["Message"]=ds["Message"].str.split()

In [21]:
ds["Message"]=ds["Message"].apply(lambda x:" ".join(x))
ds["Message"]=ds["Message"].str.replace(r"[^a-zA-Z0-9 ]","",regex=True)
ds["Message"]=ds["Message"].str.split()

In [22]:
ds.tail()

      Category                                            Message
5164         1  [this, is, the, 2nd, time, we, have, tried, 2,...
5165         0          [will, b, going, to, esplanade, fr, home]
5166         0  [pity, was, in, mood, for, that, soany, other,...
5167         0  [the, guy, did, some, bitching, but, i, acted,...
5168         0                   [rofl, its, true, to, its, name]

In [23]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5169 entries, 0 to 5168
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5169 non-null   int64
 1   Message   5169 non-null   object
dtypes: int64(1), object(1)
memory usage: 80.9+ KB

In [24]:
ds.to_csv("D:\Github\python-data-preprocessing/clean_spam_data.csv")