In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("us-shein-home_textile-3883[1].csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3882 entries, 0 to 3881
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump       39 non-null     object
 1   goods-title-link--jump href  39 non-null     object
 2   rank-title                   525 non-null    object
 3   rank-sub                     525 non-null    object
 4   price                        3882 non-null   object
 5   color-count                  1177 non-null   float64
 6   selling_proposition          2797 non-null   object
 7   discount                     1469 non-null   object
 8   goods-title-link             3843 non-null   object
dtypes: float64(1), object(8)
memory usage: 273.1+ KB

In [4]:
df.head()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,color-count,selling_proposition,discount,goods-title-link
0,"1pc Multifunctional Bean Bag Sofa (Cover Only,...",https://us.shein.com/1pc-Multifunctional-Bean-...,#2 Best Sellers,in Recliner Slipcovers,$41.70,NaN,NaN,NaN,NaN
1,1pc Tie Dye Pink Cozy Rabbit Fur Plush Blanket...,https://us.shein.com/1pc-Tie-Dye-Pink-Cozy-Rab...,NaN,NaN,$10.56,9.0,1.0k+ sold recently,-38%,NaN
2,1pc Large Foldable Food Cover Fly Proof Kitche...,https://us.shein.com/1pc-Large-Foldable-Food-C...,#8 Best Sellers,in Kitchen & Table Linens,$1.72,NaN,NaN,-18%,NaN
3,"Coral Fleece Solid Color Thickened Soft, Absor...",https://us.shein.com/Coral-Fleece-Solid-Color-...,#3 Best Sellers,in Towel Sets,$3.40,8.0,NaN,NaN,NaN
4,1pc Hand-Woven Double Layered Wood Bead Tassel...,https://us.shein.com/1pc-Hand-Woven-Double-Lay...,#10 Best Sellers,in Wall Hanging,$5.60,NaN,NaN,NaN,NaN

In [5]:
df.size

34938

In [6]:
# Errors/Assumptions
# 1.remove 1st and 2nd column because it contain only 39 records
# 2.fill rank sub and rank title with "unranked" and median()/mode()
# 3.price convert to ₹
# 4.fill color count with mean()
# 5.make selling proposition in flaot/int like 1k->1000
# 6.make discount +ve and in flaot
# 7.rename goods-title-link->product title

In [7]:
df=df.drop(columns=["goods-title-link--jump","goods-title-link--jump href"])

In [8]:
df["rank-title"].isnull().sum()

3357

In [9]:
df["rank-title"]=df["rank-title"].fillna("Unranked(New)")

In [10]:
df["rank-sub"].isnull().sum()

3357

In [11]:
df["rank-sub"]=df["rank-sub"].fillna("General-Home-Textile")

In [12]:
df["price"]=df["price"].str[1:]

In [13]:
df["price"]=df["price"].fillna("0")

In [14]:
df.loc[df["price"]=='888,888.00']

,rank-title,rank-sub,price,color-count,selling_proposition,discount,goods-title-link
367,Unranked(New),General-Home-Textile,"888,888.00",NaN,NaN,NaN,This Is A Very Goods Product Name A A A A !!! ...

In [15]:
df.drop(367,inplace=True)

In [16]:
df["price"]=df["price"].astype(float)

In [17]:
df["price"]=df["price"]*95

In [18]:
df=df.rename(columns={"price":"Price(₹)","goods-title-link":"Product_Title"})

In [19]:
df["color-count"].isnull().sum()

2704

In [20]:
df["color-count"].mode()[0]

4.0

In [21]:
df["color-count"]=df["color-count"].fillna(df["color-count"].mode()[0])

In [22]:
df["color-count"].isnull().sum()

0

In [23]:
df["selling_proposition"]=df["selling_proposition"].str[:5]

In [24]:
df["selling_proposition"]=df["selling_proposition"].str.replace(r'[+s]',"",regex=True)

In [25]:
def convert_k(val):
    str_val=str(val).lower().strip()
    if "k" in str_val:
        return int(float(str_val.replace("k",""))*1000)
    else:
        return str_val if str_val.replace(".","").isdigit() else val

In [26]:
df["selling_proposition"]=df["selling_proposition"].apply(convert_k)

In [27]:
df["selling_proposition"].isnull().sum()

1084

In [28]:
df["selling_proposition"]=df["selling_proposition"].fillna(0)

In [29]:
df["discount"].unique()

array([nan, '-38%', '-18%', '-54%', '-10%', '-25%', '-35%', '-20%',
       '-45%', '-28%', '-34%', '-57%', '-15%', '-5%', '-30%', '-40%',
       '-52%', '-67%', '-33%', '-49%', '-60%', '-36%', '-64%', '-22%',
       '-32%', '-70%', '-53%', '-48%', '-11%', '-59%', '-3%', '-76%',
       '-63%', '-12%', '-37%', '-56%', '-65%', '-19%', '-16%', '-50%',
       '-66%', '-78%', '-1%', '-31%', '-61%', '-75%', '-46%', '-44%',
       '-79%', '-43%', '-39%', '-71%', '-14%', '-26%', '-41%', '-4%',
       '-2%', '-21%', '-62%', '-58%', '-24%', '-69%', '-23%', '-13%',
       '-51%', '-6%', '-73%', '-74%', '-17%', '-8%', '-55%', '-29%',
       '-83%', '-86%', '-9%', '-81%', '-82%', '-7%', '-68%', '-77%',
       '-47%', '-27%', '-42%', '-80%', '-87%'], dtype=object)

In [30]:
df["discount"]=df["discount"].str.replace(r"[-%]","",regex=True)

In [31]:
df["discount"]=df["discount"].astype(float)

In [32]:
df["discount"]=df["discount"].fillna(0)

In [33]:
df["discount"].isnull().sum()

0

In [34]:
df["Product_Title"].isnull().sum()

39

In [35]:
df=df.dropna(subset=["Product_Title"])

In [36]:
df=df.reset_index(drop=True)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3842 entries, 0 to 3841
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   rank-title           3842 non-null   object
 1   rank-sub             3842 non-null   object
 2   Price(₹)             3842 non-null   float64
 3   color-count          3842 non-null   float64
 4   selling_proposition  3842 non-null   object
 5   discount             3842 non-null   float64
 6   Product_Title        3842 non-null   object
dtypes: float64(3), object(4)
memory usage: 210.2+ KB

In [39]:
df.to_csv("D:\Github\python-data-preprocessing\E-Commerce_Sale\E-Commerce-Home-Textile/cleaned_us-shein-home_textile-3883.csv")