In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("student_performance_updated_1000.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     952 non-null    object
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    object
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(4)
memory usage: 93.9+ KB

In [4]:
df.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

In [5]:
df.duplicated().sum()

0

In [6]:
df.isnull().sum()

StudentID                    40
Name                         34
Gender                       48
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
ParentalSupport              22
FinalGrade                   40
Study Hours                  24
Attendance (%)               41
Online Classes Taken         25
dtype: int64

In [7]:
df["StudentID"].isna().sum()

40

In [8]:
df=df.dropna(subset=["StudentID"])

In [9]:
df=df.dropna(subset=['Name'])

In [10]:
df["Gender"].isnull().sum()

44

In [11]:
df["Gender"].mode()[0]

'Male'

In [12]:
df["Gender"]=df["Gender"].fillna(df["Gender"].mode()[0])

In [13]:
df["AttendanceRate"]=df["AttendanceRate"].fillna(df["AttendanceRate"].median())

In [14]:
df["StudyHoursPerWeek"]=df["StudyHoursPerWeek"].fillna(df["StudyHoursPerWeek"].median())

In [15]:
df["PreviousGrade"].median()

78.0

In [16]:
df["PreviousGrade"]=df["PreviousGrade"].fillna(df["PreviousGrade"].median())

In [17]:
df["ExtracurricularActivities"].median()

1.0

In [18]:
df["ExtracurricularActivities"]=df["ExtracurricularActivities"].fillna(df["ExtracurricularActivities"].median())

In [19]:
df["ParentalSupport"]=df["ParentalSupport"].fillna("Medium")

In [20]:
#student who have 20>hrs have median value and who is 20< have min() value

In [21]:
g=df[df["FinalGrade"].isna()]

In [22]:
print(g[["Name","FinalGrade","StudyHoursPerWeek"]])

                   Name  FinalGrade  StudyHoursPerWeek
5                Olivia         NaN               30.0
23      David Robertson         NaN               20.0
30        David Aguilar         NaN               17.0
32         Yolanda Chen         NaN               15.0
85          Peter Welch         NaN               15.0
117     Angela Williams         NaN               22.0
120         John Warner         NaN               30.0
124        Manuel Baker         NaN                8.0
141       Amy Rodriguez         NaN               10.0
156         Dawn Morton         NaN               22.0
162         Leslie King         NaN               17.0
197  Brandon Williamson         NaN               17.0
222       Alexis Walton         NaN               10.0
225         Jean Moreno         NaN               15.0
260    Cassandra Snyder         NaN               17.0
335    Timothy Clements         NaN               17.0
351        Taylor Smith         NaN               30.0
355         Andrew Cook         NaN               15.0
373           Ian Glass         NaN               17.0
495      David Gonzalez         NaN               22.0
524          James Long         NaN               25.0
530        Julia Brooks         NaN               15.0
534        Samuel Smith         NaN               25.0
548         Brian Miles         NaN               17.0
614         David Meyer         NaN               12.0
620          David Diaz         NaN               20.0
621        Joseph Green         NaN                8.0
628   William Christian         NaN               17.0
708       Jessica Banks         NaN                8.0
745         Mary Benson         NaN               17.0
759     Virginia Medina         NaN                8.0
779   Elizabeth Nichols         NaN               25.0
875     Charles Pearson         NaN               18.0
887      Alyssa Berg MD         NaN               25.0
920        Paige Turner         NaN                8.0
962          Sean Lyons         NaN               15.0
999         Maria Walls         NaN               10.0

In [23]:
df["StudyHoursPerWeek"].median()

17.0

In [24]:
more_hrs_study=df[(df["StudyHoursPerWeek"]>=20) & (df["FinalGrade"].isna())]

In [25]:
more_hrs_study[["Name","FinalGrade","StudyHoursPerWeek"]]

                  Name  FinalGrade  StudyHoursPerWeek
5               Olivia         NaN               30.0
23     David Robertson         NaN               20.0
117    Angela Williams         NaN               22.0
120        John Warner         NaN               30.0
156        Dawn Morton         NaN               22.0
351       Taylor Smith         NaN               30.0
495     David Gonzalez         NaN               22.0
524         James Long         NaN               25.0
534       Samuel Smith         NaN               25.0
620         David Diaz         NaN               20.0
779  Elizabeth Nichols         NaN               25.0
887     Alyssa Berg MD         NaN               25.0

In [26]:
condition=(df["StudyHoursPerWeek"]>=20) & (df["FinalGrade"].isna())

In [27]:
df.loc[condition,"FinalGrade"]=df["FinalGrade"].median()

In [28]:
condition_2=(df["StudyHoursPerWeek"]<20) & (df["FinalGrade"].isna())

In [29]:
df.loc[condition_2,"FinalGrade"]=df["FinalGrade"].min()

In [30]:
df["FinalGrade"].isna().sum()

0

In [31]:
#solution for both study hours & attendance %
# 1.delete
# 2.convert to nan then fill with mean/median

In [32]:
df["Study Hours"].isnull().sum()

21

In [33]:
negative_study_hrs=df[df["Study Hours"]<0]

In [34]:
print(len(negative_study_hrs))

10

In [35]:
print(negative_study_hrs[['Name',"Study Hours","Attendance (%)"]])

                Name  Study Hours  Attendance (%)
74    Michelle Jones         -5.0           200.0
125     Jessica Lamb         -5.0           200.0
148  Michaela Powell         -5.0           200.0
220     Alicia Ortiz         -5.0           200.0
251   Michael Foster         -5.0           200.0
321  Jessica Jenkins         -5.0           200.0
366       Jill Kelly         -5.0           200.0
380  Raymond Murillo         -5.0           200.0
672   David Martinez         -5.0           200.0
798       Chad Colon         -5.0           200.0

In [36]:
df.loc[df["Study Hours"]<0,"Study Hours"]=np.nan

In [37]:
df["Study Hours"]=df["Study Hours"].fillna(df["Study Hours"].median())

In [38]:
df["Attendance (%)"].isna().sum()

39

In [39]:
high_attendance_rate=df[df["Attendance (%)"]>100]
print(len(high_attendance_rate))

10

In [40]:
print(high_attendance_rate[['Name',"Study Hours","Attendance (%)"]])

                Name  Study Hours  Attendance (%)
74    Michelle Jones          2.5           200.0
125     Jessica Lamb          2.5           200.0
148  Michaela Powell          2.5           200.0
220     Alicia Ortiz          2.5           200.0
251   Michael Foster          2.5           200.0
321  Jessica Jenkins          2.5           200.0
366       Jill Kelly          2.5           200.0
380  Raymond Murillo          2.5           200.0
672   David Martinez          2.5           200.0
798       Chad Colon          2.5           200.0

In [41]:
df.loc[df["Attendance (%)"]>100,"Attendance (%)"]=np.nan

In [42]:
df["Attendance (%)"]=df["Attendance (%)"].fillna(df["Attendance (%)"].median())

In [43]:
df["Online Classes Taken"].isna().sum()

24

In [44]:
df=df.dropna(subset=["Online Classes Taken"])

In [45]:
df.isnull().sum()

StudentID                    0
Name                         0
Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Study Hours                  0
Attendance (%)               0
Online Classes Taken         0
dtype: int64

In [46]:
df=df.reset_index(drop=True)

In [47]:
df.shape

(902, 12)

In [48]:
df=df.rename(columns={"AttendanceRate":"Attendance_Rate","StudyHoursPerWeek":"Study_Hours_Per_Week","PreviousGrade":"Previous_Grade"})

In [49]:
df=df.rename(columns={"ExtracurricularActivities":"Extra_curricular_Activities","ParentalSupport":"Parental_Support","FinalGrade":"Final_Grade"})

In [50]:
df.to_csv("D:\Github\python-data-preprocessing\Student-data-Preprocessing/cleaned_student_data.csv")