In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('trx-10k.csv')

In [3]:
df.shape

(10000, 6)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     10000 non-null  object
 1   time       10000 non-null  object
 2   card_type  9689 non-null   object
 3   city       9884 non-null   object
 4   amount     10000 non-null  float64
 5   id         10000 non-null  int64
dtypes: float64(1), int64(1), object(4)
memory usage: 468.9+ KB

In [5]:
df.describe()

             amount            id
count  1.000000e+04  10000.000000
mean   2.954735e+08     50.061200
std    1.692035e+09     28.870875
min   -9.999990e+05      1.000000
25%    1.005000e+02     25.000000
50%    3.436790e+05     50.000000
75%    9.144650e+05     74.000000
max    1.000000e+10    100.000000

In [6]:
df.head(3)

    status                 time card_type     city     amount  id
0  success  2025-09-07 10:48:00      Visa   Tehran  1427657.0  98
1  success  2025-09-20 13:10:00  MastCard   Tehran  1578078.0  52
2     fail  2025-09-29 03:27:00      Visa  Tehran    250000.0  20

In [7]:
df=df.drop_duplicates()

In [8]:
df.duplicated().sum()

0

In [9]:
df=df[['id','city','amount','card_type','status','time']]

In [10]:
text_columns=df.select_dtypes(include='object')

In [11]:
for col in text_columns:
    df[col]=df[col].str.strip()

In [12]:
for col in text_columns:
    df[col]=df[col].fillna('Unknown')

In [13]:
for col in text_columns:
    print(f" {col} : {df[col].isna().sum()}")

 city : 0
 card_type : 0
 status : 0
 time : 0

In [14]:
df['amount']=pd.to_numeric(df['amount'],errors='coerce')

In [15]:
df['amount'].min()

-999999.0

In [16]:
df=df[df['amount'] > 100]

In [17]:
df['amount'].min()

100.5

In [18]:
df=df[(df['amount'] != 9999999999.0)]

In [19]:
df['amount'].max()

1883871.0

In [20]:
df['time']=pd.to_datetime(df['time'],errors='coerce')

In [21]:
df['city']=df['city'].str.lower()

In [22]:
df['city'].unique()

array(['tehran', 'tabriz', 'shiraz', 'isfahan', 'karaj', 'ahvaz', 'thr',
       'qom', 'mashhad', 'tehr@n', 'unknown', 'thran'], dtype=object)

In [23]:
update_city={'thran':'tehran',
             'tehr@n':'tehran',
             'thr':'tehran'}

In [24]:
df['city']=df['city'].replace(update_city)

In [25]:
df['card_type'].unique()

array(['Visa', 'MastCard', 'Discover', 'Master-Card', 'Amex', 'visa',
       'MasterCard', 'Unknown', 'Vsa', 'VISA', 'Master Card'],
      dtype=object)

In [26]:
df['card_type']=df['card_type'].str.replace(' ','').str.replace('-','').str.lower()

In [27]:
update_card={'vsa':'visa',
             'mastcard':'mastercard'}

In [28]:
df['card_type']=df['card_type'].replace(update_card)

In [29]:
df['status'].unique()

array(['success', 'fail', 'Success', 'failed', 'FAIL', 'succeed'],
      dtype=object)

In [30]:
update_status={'failed':'fail',
               'succeed':'success'}
df['status']=df['status'].replace(update_status).str.lower()

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7400 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         7400 non-null   int64
 1   city       7400 non-null   object
 2   amount     7400 non-null   float64
 3   card_type  7400 non-null   object
 4   status     7400 non-null   object
 5   time       7400 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 404.7+ KB

In [32]:
print('Shape',df.shape)
print('Duplicates',df.duplicated().sum())
print("\nMissing Values")
print(df.isna().sum())
print('\n Dtypes')
print(df.dtypes)

Shape (7400, 6)
Duplicates 0

Missing Values
id           0
city         0
amount       0
card_type    0
status       0
time         0
dtype: int64

 Dtypes
id                    int64
city                 object
amount              float64
card_type            object
status               object
time         datetime64[ns]
dtype: object

In [33]:
df.reset_index(drop=True,inplace=True)

In [34]:
df.to_csv('D:\Github\python-data-preprocessing\Iranian_airlines-ds/cleaned_dataset2.csv',index=False)