In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('trx-10k.csv')

In [3]:
df.shape

(10000, 6)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   status     10000 non-null  object
 1   time       10000 non-null  object
 2   card_type  9689 non-null   object
 3   city       9884 non-null   object
 4   amount     10000 non-null  float64
 5   id         10000 non-null  int64
dtypes: float64(1), int64(1), object(4)
memory usage: 468.9+ KB

In [5]:
df.describe()

             amount            id
count  1.000000e+04  10000.000000
mean   2.954735e+08     50.061200
std    1.692035e+09     28.870875
min   -9.999990e+05      1.000000
25%    1.005000e+02     25.000000
50%    3.436790e+05     50.000000
75%    9.144650e+05     74.000000
max    1.000000e+10    100.000000

In [6]:
df.head(3)

    status                 time card_type     city     amount  id
0  success  2025-09-07 10:48:00      Visa   Tehran  1427657.0  98
1  success  2025-09-20 13:10:00  MastCard   Tehran  1578078.0  52
2     fail  2025-09-29 03:27:00      Visa  Tehran    250000.0  20

In [7]:
df=df[['id','city','amount','card_type','status','time']]

In [8]:
text_columns=df.select_dtypes(include='object')

In [9]:
for col in text_columns:
    df[col]=df[col].str.strip()

In [10]:
for col in text_columns:
    df[col]=df[col].fillna('Unknown')

In [11]:
df['amount']=pd.to_numeric(df['amount'],errors='coerce')

In [12]:
# df=df[df['amount']>1]

In [13]:
df['amount'].min()

100.5

In [14]:
a=sorted(df['amount'])
print(a[-10:])

[9999999999.0, 9999999999.0, 9999999999.0, 9999999999.0, 9999999999.0, 9999999999.0, 9999999999.0, 9999999999.0, 9999999999.0, 9999999999.0]

In [15]:
# df=df[(df['amount'] != 9999999999.0)]

In [16]:
df['amount'].max()

1883871.0

In [17]:
# a=sorted(df['amount'])
print(a[-10:])

[1883871.0, 1883871.0, 1883871.0, 1883871.0, 1883871.0, 1883871.0, 1883871.0, 1883871.0, 1883871.0, 1883871.0]

In [18]:
df[df['amount']==1883871.0]

      id     city     amount   card_type   status                 time
83    13   Tehran  1883871.0         Vsa     fail  2025-09-17 01:51:00
180   60      Qom  1883871.0        visa   failed  2025-09-23 21:21:00
360   50  Isfahan  1883871.0        Visa   failed  2025-09-05 19:40:00
429   50   Tabriz  1883871.0         Vsa  success  2025-09-08 02:30:00
468   72      THR  1883871.0  MasterCard  success  2025-09-29 12:12:00
...   ..      ...        ...         ...      ...                  ...
9702  31   Tabriz  1883871.0        Amex   failed  2025-09-29 11:11:00
9733  77    Karaj  1883871.0    Discover  success  2025-09-09 18:12:00
9737  71    Ahvaz  1883871.0        Visa  success  2025-09-20 19:51:00
9848  38   tehr@n  1883871.0        visa     fail  2025-09-30 20:33:00
9896  98   Shiraz  1883871.0     Unknown     fail  2025-09-28 14:30:00

[116 rows x 6 columns]

In [1]:
df['time']=df.to_datetime(df['time'],format='%H:%M %Y-%m-%d',errors='coerce')

NameError: name 'df' is not defined

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7400 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         7400 non-null   int64
 1   city       7400 non-null   object
 2   amount     7400 non-null   float64
 3   card_type  7400 non-null   object
 4   status     7400 non-null   object
 5   time       7400 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 404.7+ KB