In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
ds=pd.read_csv("us-shein-jewelry_and_accessories-3548.csv")

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3547 entries, 0 to 3546
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump       39 non-null     object
 1   goods-title-link--jump href  39 non-null     object
 2   rank-title                   716 non-null    object
 3   rank-sub                     716 non-null    object
 4   price                        3547 non-null   object
 5   selling_proposition          2736 non-null   object
 6   discount                     1926 non-null   object
 7   goods-title-link             3508 non-null   object
dtypes: object(8)
memory usage: 221.8+ KB

In [4]:
ds.head()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,selling_proposition,discount,goods-title-link
0,Customized Personalized Heart-Shaped Lace Name...,https://us.shein.com/Customized-Personalized-H...,#3 Best Sellers,in Customized Fashion Word Necklaces,$6.40,NaN,NaN,NaN
1,"24pcs/Set Simple Heart, Butterfly, Flower, Rhi...",https://us.shein.com/24pcs-Set-Simple-Heart-Bu...,NaN,NaN,$2.10,7.2k+ sold recently,NaN,NaN
2,"A Multi-Functional Electronic Watch With 1.44""...",https://us.shein.com/A-Multi-Functional-Electr...,#7 Best Sellers,in Women Digital Watches,$8.20,NaN,-10%,NaN
3,91pcs/Set Fashionable Elegant Vintage Multi-El...,https://us.shein.com/91pcs-Set-Fashionable-Ele...,#9 Best Sellers,in Women Jewelry Sets,$1.50,NaN,NaN,NaN
4,Multi-pack Random Mix-color Popular Bohemian R...,https://us.shein.com/Multi-pack-Random-Mix-col...,NaN,NaN,$1.10,7.4k+ sold recently,NaN,NaN

In [5]:
ds.tail()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,selling_proposition,discount,goods-title-link
3542,NaN,NaN,NaN,NaN,$10.90,NaN,NaN,Glitter Decor Flap Chain Square Bag
3543,NaN,NaN,NaN,NaN,$5.10,10+ sold recently,-7%,1pc Women's Solid Color Breathable Soft Fringe...
3544,NaN,NaN,NaN,NaN,$9.60,400+ sold recently,-7%,Boho 1pc Vintage Hollow Out Straw Cowboy Hat W...
3545,NaN,NaN,NaN,NaN,$22.10,10+ sold recently,-7%,1pc Elegant Embroidered Abaya Dress With Beaut...
3546,NaN,NaN,NaN,NaN,$2.70,1.4k+ sold recently,NaN,1 Pair Retro Western Style Geometric Turquoise...

In [6]:
# Errors/assumptions
# 1.goods-title link-jump and goods title link href are need to remove
# 2.fill rank title and rank sub with "new"& remove string text 
# 3.price convert to indian ruppe $->₹
# 4.selling proposition must be in numbers
# 5.discount should always in +ve
# 6.rename goods title link-> Product title

In [7]:
ds=ds.drop(columns=["goods-title-link--jump","goods-title-link--jump href"])

In [8]:
ds["rank-title"].isnull().sum()

2831

In [9]:
ds["rank-title"]=ds["rank-title"].fillna("Unranked(New)")

In [10]:
ds["rank-sub"].isnull().sum()

2831

In [11]:
ds["rank-sub"]=ds["rank-sub"].fillna("General_jewelry")

In [12]:
ds["price"]=ds["price"].str[1:]

In [13]:
ds["price"]=ds["price"].astype(float)

In [14]:
ds["price"]=ds["price"]*95

In [15]:
ds["price"].head()

0    608.0
1    199.5
2    779.0
3    142.5
4    104.5
Name: price, dtype: float64

In [16]:
ds["selling_proposition"].isnull().sum()

811

In [17]:
ds["selling_proposition"]=ds["selling_proposition"].str[:5]

In [18]:
ds["selling_proposition"]=ds["selling_proposition"].str.replace(r"[+s]","",regex=True)

In [19]:
def convert_k(val):
    str_val=str(val).lower().strip()
    if "k" in str_val:
        return int(float(str_val.replace("k",""))*1000)
    else:
        return int(float(str_val)) if str_val.replace(".","").isdigit() else val

In [20]:
ds["selling_proposition"]=ds["selling_proposition"].apply(convert_k)

In [21]:
ds["selling_proposition"]=ds["selling_proposition"].fillna(0)

In [22]:
ds["discount"]=ds["discount"].str.replace(r"[-%]","",regex=True)

In [23]:
ds["discount"]=ds["discount"].astype(float)

In [24]:
ds["discount"]=ds["discount"].fillna(0)

In [25]:
ds["discount"].unique()

array([ 0., 10.,  9.,  8., 11., 18.,  1., 50., 79.,  5., 80., 22.,  6.,
       20., 42., 26.,  7., 35., 46., 49., 38., 62.,  3., 30., 51., 14.,
       58., 40., 47., 57., 34., 55., 23., 19., 45., 41., 33., 61., 72.,
       36.,  4., 21., 73., 68., 60., 54., 12., 64., 32.,  2., 29., 76.,
       56., 31., 74., 37., 44., 17., 71., 27., 13., 15., 39., 63., 82.,
       43., 48., 25., 65., 67., 16., 78., 77., 69., 53., 24., 75., 28.,
       66., 59., 52., 70., 83.])

In [26]:
ds["goods-title-link"].isnull().sum()

39

In [27]:
ds=ds.dropna(subset=["goods-title-link"])

In [28]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3508 entries, 39 to 3546
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   rank-title           3508 non-null   object
 1   rank-sub             3508 non-null   object
 2   price                3508 non-null   float64
 3   selling_proposition  3508 non-null   float64
 4   discount             3508 non-null   float64
 5   goods-title-link     3508 non-null   object
dtypes: float64(3), object(3)
memory usage: 191.8+ KB

In [29]:
ds.duplicated().sum()

180

In [30]:
ds=ds.drop_duplicates()

In [31]:
ds=ds.reset_index(drop=True)

In [32]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328 entries, 0 to 3327
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   rank-title           3328 non-null   object
 1   rank-sub             3328 non-null   object
 2   price                3328 non-null   float64
 3   selling_proposition  3328 non-null   float64
 4   discount             3328 non-null   float64
 5   goods-title-link     3328 non-null   object
dtypes: float64(3), object(3)
memory usage: 156.1+ KB

In [33]:
ds.to_csv("D:\Github\python-data-preprocessing\E-Commerce_Sale\E-Commerce-Jewelry-&-Accessories/cleaned_us-shein-jewelry_and_accessories.csv")